// Keep PrimeFlex utilities used by templates and generate the Tachyon PrimeNG palette.
const fs = require('node:fs');
const path = require('node:path');
const postcss = require('postcss');
const files = fs.readdirSync('src/app', { recursive: true }).filter(file => /\.(html|ts)$/.test(file));
const tokens = new Set(files.flatMap(file => fs.readFileSync(path.join('src/app', file), 'utf8').match(/[\w:-]+/g) || []));
const css = postcss.parse(fs.readFileSync('node_modules/primeflex/primeflex.css', 'utf8'));
css.walkRules(rule => {
  const classes = [...rule.selector.matchAll(/\.((?:[\w-]|\\[:\w])+)/g)].map(match => match[1].replaceAll('\\', ''));
  if (classes.length && !classes.some(name => tokens.has(name))) rule.remove();
});
css.walkAtRules(rule => { if (rule.nodes && !rule.nodes.length) rule.remove(); });
fs.mkdirSync('src/styles/generated', { recursive: true });
fs.writeFileSync('src/styles/generated/utilities.css', '/* Generated by scripts/build-styles.cjs */\n' + css.toString());
let theme = postcss.parse(fs.readFileSync('node_modules/primeng/resources/themes/lara-light-blue/theme.css', 'utf8'));
theme.walkAtRules('font-face', rule => rule.remove());
const palette = { '#3b82f6': '#DB2532', '#2563eb': '#bf202c', '#1d4ed8': '#a51c26', '#1e40af': '#8e1821', '#60a5fa': '#e95a65', '#93c5fd': '#f19aa2', '#bfdbfe': '#f7c2c7', '#dbeafe': '#fbe0e3', '#eff6ff': '#fff1f2' };
theme = theme.toString().replace(/#[a-f\d]{6}/gi, color => palette[color.toLowerCase()] || color).replaceAll('"Inter var", sans-serif', 'var(--font-sans)');
fs.writeFileSync('src/styles/generated/theme.css', '/* Tachyon palette derived from installed PrimeNG Lara theme. */\n' + theme);
